# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-27 12:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shortener', '0008_auto_20170525_1739'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClickEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
                ('big_url', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shortener.BigUrl')),
            ],
        ),
    ]
