# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-01-04 17:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bigurl',
            name='shortcode',
            field=models.CharField(default='xyz', max_length=15),
        ),
    ]
