# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-01-04 17:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0002_bigurl_shortcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bigurl',
            name='shortcode',
            field=models.CharField(default='xyz', max_length=15, unique=True),
        ),
    ]
