# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-17 10:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0006_auto_20170517_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bigurl',
            name='shortcode',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
    ]
