# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-25 17:39
from __future__ import unicode_literals

from django.db import migrations, models
import shortener.validators


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0007_auto_20170517_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bigurl',
            name='url',
            field=models.CharField(max_length=220, validators=[shortener.validators.validate_url, shortener.validators.validate_dot_com]),
        ),
    ]
